
import style from  "./globals.css";
import Navigation from "@/components/navigation"; "@/components/navigation"


export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={style.html}>
      <body> 
        
        <Navigation/>
        {children}
       
      </body>
      
    </html>
  );
}

